[build]
publish = "dist"
command = "pnpm run build"

[build.environment]
NODE_VERSION = "20"

[[redirects]]
from = "/.well-known/*"
to = "/.well-known/:splat"
status = 200

#[[redirects]]
#from = "/*"
#to = "/index.html"
#status = 200

[[redirects]]
  from = "/slidess/01_uvod_do_python/*"
  to = "/slidess/01_uvod_do_python/index.html"
  status = 200

[[redirects]]
  from = "/slidess/02_input_konverze_text/*"
  to = "/slidess/02_input_konverze_text/index.html"
  status = 200